name: Generate GitHub Stats

on:
  workflow_call: # Permite ser chamado por outros workflows
    secrets:
      TOKEN:
        required: true
      REPOSITORY_OWNER:
        required: true

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install @octokit/rest
        
      - name: Force sync with remote
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin
          git reset --hard origin/main
          
      - name: Generate GitHub stats card
        run: node scripts/github-stats-generator.js
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ secrets.REPOSITORY_OWNER }}
          
      - name: Update README with stats
        run: node scripts/update-readme-stats.js
        
      - name: Commit and push changes
        run: |
          git add README.md assets/github-stats*.svg assets/github-stats-data.json
          git diff --staged --quiet || git commit -m "📊 update github stats card"
          git push
