name: Update Tech Stack

on:
  workflow_call: # Permite ser chamado por outros workflows

jobs:
  update-tech:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Force sync with remote
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin
          git reset --hard origin/main
          
      - name: Generate Tech Stack SVGs
        run: node scripts/tech-stack-svg-generator.js
        
      - name: Update README tech stack
        run: node scripts/update-readme-tech.js
        
      - name: Commit and push changes
        run: |
          git add README.md assets/tech-stack-*.svg data/tech-stack.json
          git diff --staged --quiet || git commit -m "🚀 update tech stack SVGs and README"
          git push
