name: Update Tech Stack

on:
  schedule:
    - cron: "0 0 * * 1" # Toda segunda-feira
  workflow_dispatch:
  push:
    paths:
      - 'data/tech-stack.json'

jobs:
  update-tech:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Update README tech stack
        run: node scripts/update-readme-tech.js
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "atualiza tech stack no README"
          git push
