name: Update Tech Stack

on:
  push:
    branches:
      - main
    paths:
      - 'data/tech-stack.json'
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1" # Every Monday
  workflow_dispatch:

jobs:
  update-tech:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
          
      - name: Update README tech stack
        run: node scripts/update-readme-tech.js
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "update tech stack in README"
          git push
