name: Weekly Activity Graph

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday
  workflow_dispatch:

jobs:
  generate-weekly-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Generate weekly activity graph
        run: node scripts/generate-weekly-activity.js
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/weekly-activity.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update weekly activity graph" && git push) 